name: Update Blocklist

on:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  update-blocklist:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      CI_COMMIT_MESSAGE: Update blocklist feeds
      CI_COMMIT_AUTHOR: GitHub Action
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
        
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
        
    - name: Create required directories
      run: |
        mkdir -p source
        mkdir -p dist
        
    - name: Run blocklist generator
      run: bun run generate.js
      
    - name: Commit and push changes
      run: |
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "action@users.noreply.github.com"
        git add source/ dist/
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "${{ env.CI_COMMIT_MESSAGE }} - $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
          git push
        fi
