name: Update Blocklist

on:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  update-blocklist:
    runs-on: ubuntu-latest
    container:
      image: oven/bun:alpine
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
        
    - name: Create required directories
      run: |
        mkdir -p source
        mkdir -p dist
        
    - name: Run blocklist generator
      run: bun run generate.js
      
    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Update blocklist feeds - ${{ github.run_id }}"
        file_pattern: "source/ dist/"
